service: bambee-challenge
custom:
  aws:
    region: us-east-1
    accountId: 933545778475

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 900
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:${self:custom.aws.region}:${self:custom.aws.accountId}:table/bambee-${opt:stage}-tasks
    - Effect: Allow
      Action:
        - sqs:*
      Resource: arn:aws:sqs:${self:custom.aws.region}:${self:custom.aws.accountId}:bambee-*
    - Effect: Allow
      Action:
        - lambda:*
      Resource: *
functions:
  - ${file(src/auth/function.yaml)}
  - ${file(src/data/function.yaml)}
  - ${file(src/api/function.yaml)}

resources:
  Resources:
    CreateTaskQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: bambee-${opt:stage}-task-createTask
        VisibilityTimeout: 900
        DelaySeconds: 0
    UpdateTaskV1Queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: bambee-${opt:stage}-task-update-v1
        VisibilityTimeout: 900
        DelaySeconds: 0
    UpdateTaskV2Queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: bambee-${opt:stage}-task-update-v2
        VisibilityTimeout: 900
        DelaySeconds: 0
    UserTasksTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: taskId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: taskId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: bambee-${opt:stage}-tasks
plugins:
  - serverless-plugin-typescript

package:
  exclude:
    - .npm/**
    - serverless/**
    - .idea/**
    - node_modules/aws-sdk/**
